apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: longread-blog

# Патчи для dev окружения
patchesStrategicMerge:
  - replicas-patch.yaml
  - resources-patch.yaml

# Переменные окружения для dev
configMapGenerator:
  - name: longread-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development

# Образы для dev (можно переопределить теги)
images:
  - name: longread-backend
    newTag: latest
  - name: longread-frontend
    newTag: latest

commonLabels:
  environment: development
